[package]
name = "rust-rpg-designer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "*"
wasm-bindgen = "*"
yew = "*"
wasm-logger = "*"
log = "*"
js-sys = "*"

[dependencies.web-sys]
version = "*"
features = ["HtmlFormElement", "FormData"]
